### PR TITLE
Add CW event bridge notification types

### PR DESCRIPTION
**Pull request by xquek**
### Notes

I base my types using examples from 
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-and-eventbridge.html
and 
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudwatch/client/describe_alarms.html

In [cloudwatch-and-eventbridge.html](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-and-eventbridge.html), there are several different event types (or detail-type). I was wondering do we need to create different type def for different event. (detail-type)

I am also not sure how accurate the examples are - if you know of a better source for reference, do let me know!

I havent add any UT, let. me know what i should add.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist

All of these are optional:

- [X] I have performed a self-review of my own code
- [X] I have run `./scripts/before_commit.sh` to follow the style guidelines of this project ( i recieved: mypy_boto3_builder/type_maps/typed_dicts.py:209: unused variable 'CloudwatchEventTypeDef' (60% confidence))
- [ ] I have tested my code changes

Thank you!

### CODE REVIEW

**Comment by vemel** [comment]
Thank you for your contribution!

Looks good to me. Please test how it works and move PR to ready for review once tested.

Let me know if you need any help with testing.

**Comment by xquek** [comment]
Thanks @vemel, what are your recommended steps for testing? do i write tests for it or it is more of a manual testing?

**Comment by vemel** [comment]
I do not think we need automated tests, so manual testing is enough.

1. As far as I can see, your code does not add TypeDefs to CloudWatch service package. Please add this logic.

Find `type_defs = result.get_type_defs()` line in `mypy_boto3_builder/parsers/service_package_parser.py`. This is where you want to add your new type annotations.

```python
from mypy_boto3_builder.service_name import ServiceNameCatalog

...

type_defs = result.get_type_defs()

# Add hardcoded CloudwatchEvent type definitions to cloudwatch service
if self.service_name == ServiceNameCatalog.cloudwatch:
   type_defs.add(CloudwatchEventTypeDef)
```

2. Build and install `mypy-boto3-cloudwatch`

```bash
poetry shell

# generate ./mypy_boto3_output/mypy_boto3_cloudwatch_package
./scripts/build.sh -s cloudwatch--product boto3-service

#  install generated `mypy-boto3-cloudwatch`
./scripts/install.sh cloudwatch
```

3. Write and run a code sample to check your changes work

```python
from mypy_boto3_cloudwatch.type_defs import CloudwatchEventTypeDef

my_event: CloudwatchEventTypeDef = {...}
```

Run `pyright` or `mypy` on your code sample and check if it verifies type cvorrectly.

**Comment by vemel** [comment]
@xquek please let me know if you have time to finish this PR. If not - I can merge it as it is and do the rest.

**Comment by xquek** [comment]
Hi @vemel, apologies havent had the time to work on it this week yet.  i think it might be faster for you to merge it and complete it  - sorry about that

**Comment by vemel** [comment]
No worries. Please remove `draft` from the PR once you stop working on the PR.

**Comment by xquek** [comment]
Done! And thank you,!

**Pull request merged**
